In [1]:
import cv2

In [2]:
img=cv2.imread("galaxy.jpg",0)

print(type(img))

<class 'numpy.ndarray'>


In [3]:
print(img)

[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]


In [4]:
print(img.shape)

(1485, 990)


In [5]:
print(img.ndim)

2


In [6]:
resized_image=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))

In [7]:
cv2.imshow("Galaxy",resized_image)
cv2.imwrite("Galaxy_resized.jpg",resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()